"""empty message

Revision ID: 991643d814b4
Revises: f841e0756354
Create Date: 2023-10-05 16:10:55.609302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991643d814b4'
down_revision = 'f841e0756354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourites')
    # ### end Alembic commands ###
