"""empty message

Revision ID: f841e0756354
Revises: ebff2cffecc5
Create Date: 2023-10-05 12:40:32.012153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f841e0756354'
down_revision = 'ebff2cffecc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint('characters_gender_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_unique_constraint('characters_gender_key', ['gender'])

    # ### end Alembic commands ###
